### ISSUE TITLE
site.USER_SITE

### ISSUE THREAD

**Issue by unwave** [amb/blender_pip#2]
https://docs.python.org/3/library/site.html#site.USER_SITE
> Path to the user site-packages for the running Python. Can be None if getusersitepackages() hasn’t been called yet.

Can it cause any bugs? May be it is better to use `site.getusersitepackages()`?

**Comment by amb** [comment]
Thanks. I added it to the latest master branch.

**Comment by unwave** [comment]
What is your opinion on where to store site-packages? The main context here is using pip to install platform-dependent modules.
1. **Blender's site-packages folder** 
It causes re-installation for every new Blender instance, even if Blender copies the previous version's add-ons to the new one. Also, Blender may not have permission to write here. But this allows for importing packages just with `import` without a need to add to `sys.path`.
2. **USER_SITE**
It is not ideal to interact with a person's Python environment. Like updating modules can potentially break something. But it is reasonable and allows for reusing packages.
3. **Add-on's folder**
In this case, packages become sealed in and require the add-on to be enabled if even it adds them to `sys.path`, but this makes an add-on independent and complete.

**Comment by amb** [comment]
I don't think either 1. or 3. are feasible. 1. Because it can be write protected, and you have to re-install for every Blender. 3. Because it works only for some packages, if there are any complex dependency management done by the OS, it's really difficult. Plus MacOS and Linux can't dynamically link from a relative folder to the executable, as far as I'm aware. Both 1 and 3 seem to have a lot of gotchas and traps.

Which leaves 2. Which isn't ideal, but is workable. If you have any complex Python package management in your system, you would be using Anaconda to do that anyways. Just disabling version number use from PIP would probably get half-way there (getting custom packages into Blender). 

Like I said, not ideal, but much better than not being able to use custom Python packages at all.

**Comment by unwave** [comment]
* What can be wrong with this?
```py
import bpy
import sys
import os

script_file_directory = os.path.dirname(os.path.realpath(__file__))
site_packages_path = os.path.join(script_file_directory, "site-packages")

if not os.path.exists(site_packages_path):
    os.makedirs(site_packages_path)

sys.path.append(site_packages_path)

try:
    import xxhash
    from PIL import Image as pillow_image
except:
    import subprocess
    python_binary =  bpy.app.binary_path_python
    try:
        subprocess.run([python_binary, '-m', 'ensurepip'], check=True)
        subprocess.run([python_binary, '-m', 'pip', 'install', 'xxhash', '-t', site_packages_path], check=True)
        subprocess.run([python_binary, '-m', 'pip', 'install', 'Pillow', '-t', site_packages_path], check=True)
    except subprocess.SubprocessError as error:
        print(error.output)
```
* What do you think about [this approach](https://github.com/eliemichel/LilySurfaceScraper/tree/master/blender/LilySurfaceScraper/site-packages/lxml) by eliemichel?

**Comment by amb** [comment]
For this particular Blender addon, no point probably, as the purpose is to install Python modules for all Blender addons.

For individual Blender addons, that could be a good idea, depending on how PIP works in installing to custom site-packages folders.

For blender-pip addon, it could be possible for the addons to just define requirements.txt and then use blender-pip to scan all the folders and run pip to install the Python modules into the addon folder for each addon. That way all Blender addons could just define requirements.txt without having to write any (possibly broken) Python package management code.

Just my thoughts about it.

**Comment by unwave** [comment]
What about [the modules folder](https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html?highlight=./scripts/addons/modules/*.py#path-layout)?

**Comment by amb** [comment]
Same weakness as just copying the Python addon in the addon folder: can't do updates and it's locked to a certain binary/Blender version.

**Comment by unwave** [comment]
I think you can use `--target` with `--upgrade` as it suggests: `WARNING: Target directory <path> already exists. Specify --upgrade to force replacement.` And about the lock, do you want to say Blender has no write permission in its addons folder? How when does it install addons? Can you give an example? It has to have [the permission](https://developer.blender.org/T77962#956228).

**Comment by amb** [comment]
So what you're suggesting is to use PIP to install Python packages into the Blender modules folder?

**Comment by unwave** [comment]
The fact that it is auto-added to `sys.path` says it was designed to be such a folder. So it can work without any addons, much like the native Blender's site-packages folder.

I don't use the Blender's addon folder because it makes it harder to control addons when changing versions. I like to use a custom script folder and put them there manually.

Maybe adding an option will be a good idea. And set to use `modules` as default to accommodate the Blender addon management design.
