### ISSUE TITLE
Irrelevant issue with 2.92 in Alpha

### ISSUE THREAD

**Issue by unity2k** [amb/blender_pip#3]
Titled as irrelevant as this is in 2.92 and I'm aware it could disappear on its own tomorrow but I thought you might see something in the log that could be more than me impatiently using alpha versions of Blender:

![image](https://user-images.githubusercontent.com/3246704/100909437-f7f31900-3489-11eb-9354-c1e57774adc2.png)

**Comment by amb** [comment]
Thanks, I'll keep an eye on it.

**Comment by unity2k** [comment]
Automagically this was working on a new notebook with 2.92 so I went in and removed everything from my c:\program files\blender\blender foundation directory and reinstalled 2.92 on my desktop and everything works again here so I'm closing this issue.

**Comment by unity2k** [comment]
I'm reopening this because the issue came back after I updated the version of Blender with a new nightly build. If I copy over the old (yesterdays) installation, I get the problem. I have to delete the old version first.

**Comment by amb** [comment]
Closing because old issue. If the issue still remains, please notify me.
