### ISSUE TITLE
Extremely minor: Use 'sys.executable' instead of 'binary_path_python'

### ISSUE THREAD

**Issue by alinsavix** [amb/blender_pip#4]
Starting blender with blender_pip enabled gives the following warning on the console:

```
/Users/<user>/Library/Application Support/Blender/2.91/scripts/addons/blender_pip/__init__.py:34: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
```

Where line 34 is (surprise):

```
python_bin = bpy.app.binary_path_python 
```

It looks like `sys.executable` has existed since roughly the dawn of time, and seems to be correctly set  by Blender's internal python, so it shouldn't be harmful to swap out, just to get one fewer warning messages on the blender console.

**Comment by amb** [comment]
This would be a good PR if someone wants to implement it. It might be some time before I get back to this project.

**Comment by amb** [comment]
https://github.com/amb/blender_pip/pull/6
