### ISSUE TITLE
Console warning in 2.93 Alpha

### ISSUE THREAD

**Issue by unity2k** [amb/blender_pip#5]
From the console when starting Blender 2.93 with Python 3.9:

Blender PIP user site: C:\users....\appdata\roaming\Python\Python39\site-packages
C:\users\....\....\....\blender_pip\_init_.py:36: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'! python_bin = bpy.app.binary_path_python

My question is, is this an error connected to Python 3.9 or has this always been there even with Python 3.7 and I'd simply not noticed?

**Comment by amb** [comment]
Blender Python API is in constant flux, so they might have just added it lately.

**Comment by amb** [comment]
Duplicate https://github.com/amb/blender_pip/issues/4
