### ISSUE TITLE
Does not work with Blender 3.0

### ISSUE THREAD

**Issue by alinsavix** [amb/blender_pip#7]
Under Blender 3.0, the addon panel for Python Module Manager no longer offers the interface for listing/installing/removing modules -- it just shows the basic information (version, description, etc) for the addon, but none of the functional bits. It would be absolutely lovely to see an update to fix this!

(attached a screenshot of the entire panel to show this, though I doubt you'll need it!)

<img width="443" alt="image" src="https://user-images.githubusercontent.com/25068788/144685794-74909ef9-0760-49b5-940b-56da97d07dba.png">

**Comment by amb** [comment]
Try https://github.com/amb/blender_pip/releases/tag/1.0.6

**Comment by alinsavix** [comment]
Aha, works much better now.  Thanks for the update! <3
